2025-04-19T12:18:59.093Z INFO     [ScalpXRX_BTC_USDT-USDT:383] [92mLIVE MODE[0m
2025-04-19T12:18:59.093Z INFO     [ScalpXRX_BTC_USDT-USDT:388] Loading markets for bybit...
2025-04-19T12:18:59.341Z CRITICAL [ScalpXRX_BTC_USDT-USDT:402] [91mExchange init failed: bybit GET https://api.bybit.com/v5/asset/coin/query-info? 403 Forbidden <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 6b8pkr8RsMDhMwbHKxjR7sAi1meelIjRoxdqsak9iI-ZOz2IQJM1bA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>[0m
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 577, in fetch
    response.raise_for_status()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bybit.com/v5/asset/coin/query-info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 389, in initialize_exchange
    exchange.load_markets(reload=True)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1512, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 1599, in fetch_currencies
    response = self.privateGetV5AssetCoinQueryInfo(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4394, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4388, in fetch2
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4379, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 595, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1691, in handle_http_status_code
    raise ErrorClass(self.id + ' ' + method + ' ' + url + ' ' + codeAsString + ' ' + reason + ' ' + body)
ccxt.base.errors.RateLimitExceeded: bybit GET https://api.bybit.com/v5/asset/coin/query-info? 403 Forbidden <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Amazon CloudFront distribution is configured to block access from your country.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 6b8pkr8RsMDhMwbHKxjR7sAi1meelIjRoxdqsak9iI-ZOz2IQJM1bA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
2025-04-19T12:18:59.366Z CRITICAL [ScalpXRX_BTC_USDT-USDT:1017] Exchange init failed.
2025-04-19T12:19:31.172Z INFO     [ScalpXRX_BTC_USDT-USDT:383] [92mLIVE MODE[0m
2025-04-19T12:19:31.173Z INFO     [ScalpXRX_BTC_USDT-USDT:388] Loading markets for bybit...
2025-04-19T12:19:47.932Z INFO     [ScalpXRX_BTC_USDT-USDT:399] [92mExchange initialized. Balance: 12.2350 USDT[0m
2025-04-19T12:19:47.936Z INFO     [ScalpXRX_BTC_USDT-USDT:949] --- Cycle Start: BTC/USDT:USDT (5) ---
2025-04-19T12:19:50.452Z ERROR    [ScalpXRX_BTC_USDT-USDT:1002] Cycle error: 'module' object is not callable
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 962, in analyze_and_trade_symbol
    analyzer = TradingAnalyzer(klines_df, lg, config, market_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 505, in __init__
    self.calculate_indicators()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 535, in calculate_indicators
    self._calculate_momentum()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 569, in _calculate_momentum
    mom = ta.momentum(df['close'], length=self.config["momentum_period"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-04-28T14:04:26.962Z INFO     [ScalpXRX_BTC_USDT-USDT:373] [92mLIVE MODE[0m
2025-04-28T14:04:26.963Z INFO     [ScalpXRX_BTC_USDT-USDT:378] Loading markets for bybit...
2025-04-28T14:04:28.939Z CRITICAL [ScalpXRX_BTC_USDT-USDT:392] [91mExchange init failed: bybit {"retCode":10003,"retMsg":"API key is invalid.","result":{},"retExtInfo":{},"time":1745849069362}[0m
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 379, in initialize_exchange
    exchange.load_markets(reload=True)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1512, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 1599, in fetch_currencies
    response = self.privateGetV5AssetCoinQueryInfo(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4394, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4390, in fetch2
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4379, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 621, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 8838, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4783, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bybit {"retCode":10003,"retMsg":"API key is invalid.","result":{},"retExtInfo":{},"time":1745849069362}
2025-04-28T14:04:28.962Z CRITICAL [ScalpXRX_BTC_USDT-USDT:1021] Exchange init failed.
2025-04-28T14:05:47.434Z INFO     [ScalpXRX_BTC_USDT-USDT:373] [92mLIVE MODE[0m
2025-04-28T14:05:47.435Z INFO     [ScalpXRX_BTC_USDT-USDT:378] Loading markets for bybit...
2025-04-28T14:05:57.557Z CRITICAL [ScalpXRX_BTC_USDT-USDT:392] [91mExchange init failed: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1745849147436],server_timestamp[1745849156295],recv_window[5000]","result":{},"retExtInfo":{},"time":1745849156295}[0m
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 379, in initialize_exchange
    exchange.load_markets(reload=True)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1512, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 1599, in fetch_currencies
    response = self.privateGetV5AssetCoinQueryInfo(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4394, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4388, in fetch2
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4379, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 621, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 8838, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4783, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidNonce: bybit {"retCode":10002,"retMsg":"invalid request, please check your server timestamp or recv_window param. req_timestamp[1745849147436],server_timestamp[1745849156295],recv_window[5000]","result":{},"retExtInfo":{},"time":1745849156295}
2025-04-28T14:05:57.592Z CRITICAL [ScalpXRX_BTC_USDT-USDT:1021] Exchange init failed.
2025-04-28T14:06:30.402Z INFO     [ScalpXRX_BTC_USDT-USDT:373] [92mLIVE MODE[0m
2025-04-28T14:06:30.407Z INFO     [ScalpXRX_BTC_USDT-USDT:378] Loading markets for bybit...
2025-04-28T14:06:31.791Z CRITICAL [ScalpXRX_BTC_USDT-USDT:392] [91mExchange init failed: bybit {"retCode":10003,"retMsg":"API key is invalid.","result":{},"retExtInfo":{},"time":1745849192715}[0m
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 379, in initialize_exchange
    exchange.load_markets(reload=True)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 1512, in load_markets
    currencies = self.fetch_currencies()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 1599, in fetch_currencies
    response = self.privateGetV5AssetCoinQueryInfo(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/types.py", line 35, in unbound_method
    return _self.request(self.path, self.api, self.method, params, config=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4394, in request
    return self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4390, in fetch2
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4379, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 621, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/bybit.py", line 8838, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/ccxt/base/exchange.py", line 4783, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: bybit {"retCode":10003,"retMsg":"API key is invalid.","result":{},"retExtInfo":{},"time":1745849192715}
2025-04-28T14:06:31.815Z CRITICAL [ScalpXRX_BTC_USDT-USDT:1021] Exchange init failed.
2025-04-28T14:07:14.261Z INFO     [ScalpXRX_BTC_USDT-USDT:373] [92mLIVE MODE[0m
2025-04-28T14:07:14.262Z INFO     [ScalpXRX_BTC_USDT-USDT:378] Loading markets for bybit...
2025-04-28T14:07:25.170Z INFO     [ScalpXRX_BTC_USDT-USDT:389] [92mExchange initialized. Balance: 10.2844 USDT[0m
2025-04-28T14:07:25.171Z INFO     [ScalpXRX_BTC_USDT-USDT:952] --- Cycle Start: BTC/USDT:USDT (5) ---
2025-04-28T14:07:27.237Z ERROR    [ScalpXRX_BTC_USDT-USDT:1005] Cycle error: 'module' object is not callable
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 965, in analyze_and_trade_symbol
    analyzer = TradingAnalyzer(klines_df, lg, config, market_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 502, in __init__
    self.calculate_indicators()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 531, in calculate_indicators
    self._calculate_momentum()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 565, in _calculate_momentum
    mom = ta.momentum(df['close'], length=self.config["momentum_period"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
2025-04-28T14:07:37.248Z INFO     [ScalpXRX_BTC_USDT-USDT:952] --- Cycle Start: BTC/USDT:USDT (5) ---
2025-04-28T14:07:39.481Z ERROR    [ScalpXRX_BTC_USDT-USDT:1005] Cycle error: 'module' object is not callable
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 965, in analyze_and_trade_symbol
    analyzer = TradingAnalyzer(klines_df, lg, config, market_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 502, in __init__
    self.calculate_indicators()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 531, in calculate_indicators
    self._calculate_momentum()
  File "/data/data/com.termux/files/home/worldguide/livewirex.py", line 565, in _calculate_momentum
    mom = ta.momentum(df['close'], length=self.config["momentum_period"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
